indexing-settings:
  sites:
    - url: https://metanit.com/
      name: Metanit
#    - url: https://sergeybezrukov.ru/
#      name: Bezrukov
#    - url: https://www.lenta.ru/
#      name: Lenta.ru
    - url: http://playback.ru/
      name: Playback.ru
#    - url: https://dimonvideo.ru/
#      name: DimonVideo
server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: MyNewPass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        order_inserts: true
        jdbc:
          batch_size: 50000
    hibernate:
      ddl-auto: update
    show-sql: false
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate:
      SQL: ERROR
#      orm.jdbc.bind: TRACE
  file: hibernate.log

